// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYgxNPeE-JuY1A0Cl6PVNYB62IbkPpSyw',
    appId: '1:655691797618:web:92ef4c96e64ecb1caa1eeb',
    messagingSenderId: '655691797618',
    projectId: 'finalyearproject-99c04',
    authDomain: 'finalyearproject-99c04.firebaseapp.com',
    storageBucket: 'finalyearproject-99c04.firebasestorage.app',
    measurementId: 'G-BRMSTS7PCB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEpHTJuhzAT2WpXt9mnHcrwP-9bj0tWW0',
    appId: '1:655691797618:android:6b9c9973e8a2e94caa1eeb',
    messagingSenderId: '655691797618',
    projectId: 'finalyearproject-99c04',
    storageBucket: 'finalyearproject-99c04.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDf6pd7DjS68JzrYdxUV-7Qrsv_ywQ-xZ4',
    appId: '1:655691797618:ios:37994d01e7bc0d3daa1eeb',
    messagingSenderId: '655691797618',
    projectId: 'finalyearproject-99c04',
    storageBucket: 'finalyearproject-99c04.firebasestorage.app',
    iosBundleId: 'com.example.finalYearProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDf6pd7DjS68JzrYdxUV-7Qrsv_ywQ-xZ4',
    appId: '1:655691797618:ios:37994d01e7bc0d3daa1eeb',
    messagingSenderId: '655691797618',
    projectId: 'finalyearproject-99c04',
    storageBucket: 'finalyearproject-99c04.firebasestorage.app',
    iosBundleId: 'com.example.finalYearProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYgxNPeE-JuY1A0Cl6PVNYB62IbkPpSyw',
    appId: '1:655691797618:web:958687d157bc3eb3aa1eeb',
    messagingSenderId: '655691797618',
    projectId: 'finalyearproject-99c04',
    authDomain: 'finalyearproject-99c04.firebaseapp.com',
    storageBucket: 'finalyearproject-99c04.firebasestorage.app',
    measurementId: 'G-1818D7NDLW',
  );
}
